{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error processing dataset 75287a14-099e-40e0-a8cc-eed8dd4e3a0a\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/dataland/scheduled_processor.py\", line 26, in run_scheduled_processing\n",
      "    review_dataset(data_id)\n",
      "    ~~~~~~~~~~~~~~^^^^^^^^^\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/review/dataset_reviewer.py\", line 14, in review_dataset\n",
      "    relevant_pages_pdf_reader = pages_provider.get_relevant_pages_of_pdf(data_collection)\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/pages/pages_provider.py\", line 21, in get_relevant_pages_of_pdf\n",
      "    ).datapoint.data_source.file_reference\n",
      "                            ^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'file_reference'\n",
      "Error processing dataset c8b4fc6b-631f-4876-bd86-e326c50c64ac\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/dataland/scheduled_processor.py\", line 26, in run_scheduled_processing\n",
      "    review_dataset(data_id)\n",
      "    ~~~~~~~~~~~~~~^^^^^^^^^\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/review/dataset_reviewer.py\", line 14, in review_dataset\n",
      "    relevant_pages_pdf_reader = pages_provider.get_relevant_pages_of_pdf(data_collection)\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/pages/pages_provider.py\", line 21, in get_relevant_pages_of_pdf\n",
      "    ).datapoint.data_source.file_reference\n",
      "                            ^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'file_reference'\n",
      "Error processing dataset 9a3ec569-3a29-4450-8ba3-95bc352f5db3\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/dataland/scheduled_processor.py\", line 26, in run_scheduled_processing\n",
      "    review_dataset(data_id)\n",
      "    ~~~~~~~~~~~~~~^^^^^^^^^\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/review/dataset_reviewer.py\", line 14, in review_dataset\n",
      "    relevant_pages_pdf_reader = pages_provider.get_relevant_pages_of_pdf(data_collection)\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/pages/pages_provider.py\", line 21, in get_relevant_pages_of_pdf\n",
      "    ).datapoint.data_source.file_reference\n",
      "                            ^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'file_reference'\n",
      "Error processing dataset ddb9dadd-9d3f-42bb-bc7b-5395136ae4a3\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/dataland/scheduled_processor.py\", line 26, in run_scheduled_processing\n",
      "    review_dataset(data_id)\n",
      "    ~~~~~~~~~~~~~~^^^^^^^^^\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/review/dataset_reviewer.py\", line 14, in review_dataset\n",
      "    relevant_pages_pdf_reader = pages_provider.get_relevant_pages_of_pdf(data_collection)\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/pages/pages_provider.py\", line 21, in get_relevant_pages_of_pdf\n",
      "    ).datapoint.data_source.file_reference\n",
      "                            ^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'file_reference'\n",
      "Error processing dataset 677ec4dc-993e-4fe7-865a-b5a357eb693b\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/dataland/scheduled_processor.py\", line 26, in run_scheduled_processing\n",
      "    review_dataset(data_id)\n",
      "    ~~~~~~~~~~~~~~^^^^^^^^^\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/review/dataset_reviewer.py\", line 14, in review_dataset\n",
      "    relevant_pages_pdf_reader = pages_provider.get_relevant_pages_of_pdf(data_collection)\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/pages/pages_provider.py\", line 21, in get_relevant_pages_of_pdf\n",
      "    ).datapoint.data_source.file_reference\n",
      "                            ^^^^^^^^^^^^^^\n",
      "AttributeError: 'NoneType' object has no attribute 'file_reference'\n",
      "Error processing dataset 099602d5-38eb-4a97-8ed8-49b212091dbb\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/dataland/scheduled_processor.py\", line 26, in run_scheduled_processing\n",
      "    review_dataset(data_id)\n",
      "    ~~~~~~~~~~~~~~^^^^^^^^^\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/review/dataset_reviewer.py\", line 18, in review_dataset\n",
      "    report = NuclearAndGasReportGenerator().generate_report(relevant_pages=readable_text, dataset=data_collection)\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/review/report_generator/nuclear_and_gas_report_generator.py\", line 51, in generate_report\n",
      "    self.report.general.taxonomy_non_eligible = non_eligible_report_generator.build_taxonomy_non_eligible_report(\n",
      "                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^\n",
      "        dataset=dataset, relevant_pages=relevant_pages\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "    )\n",
      "    ^\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/review/report_generator/non_eligible_report_generator.py\", line 23, in build_taxonomy_non_eligible_report\n",
      "    nuclearAndGasTaxonomyNonEligibleRevenue=build_non_eligible_report_frame(dataset, relevant_pages, \"Revenue\"),\n",
      "                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/review/report_generator/non_eligible_report_generator.py\", line 32, in build_non_eligible_report_frame\n",
      "    prompted_values = NumericValueGenerator.get_taxonomy_non_eligible(relevant_pages, kpi)\n",
      "  File \"/Users/falkschnizer/DatalandQALab/src/dataland_qa_lab/review/numeric_value_generator.py\", line 63, in get_taxonomy_non_eligible\n",
      "    float_results = [float(value) for value in non_eligible_values]\n",
      "                     ~~~~~^^^^^^^\n",
      "ValueError: could not convert string to float: 'n.a.'\n"
     ]
    }
   ],
   "source": [
    "from dataland_qa_lab.dataland import scheduled_processor\n",
    "\n",
    "scheduled_processor.run_scheduled_processing(1)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
